databases:
  - name: university-platform-db
    databaseName: university_platform_production
    user: university_platform
    plan: free

services:
  - type: web
    name: university-platform-api
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server -p $PORT -e $RAILS_ENV"
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: UNSPLASH_ACCESS_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: university-platform-db
          property: connectionString